### ISSUE TITLE
Incompatible with JuMP v1.2 due to removal of nlp_data

### ISSUE THREAD

**Issue by jwharington** [infiniteopt/InfiniteOpt.jl#280]
optimize! fails due to use of nlp_data which is removed in JuMP v1.2.0

**Comment by odow** [comment]
Ah. Looks like we missed removing this line:
https://github.com/infiniteopt/InfiniteOpt.jl/blob/038965f71cce770f85cf30de62a35f73fef19554/src/optimize.jl#L489

**Comment by pulsipher** [comment]
@jwharington Thank you for reporting this. This should be resolved with #281. Once, it is merged and all looks good, I will make a new release of InfiniteOpt.
