### ISSUE TITLE
Failure with polynomial dynamics in OC problem

### ISSUE THREAD

**Issue by baggepinnen** [infiniteopt/InfiniteOpt.jl#339]
The following problem solves well, but changing the dynamics `@constraint(m, ∂(v, t) == u)` to `@constraint(m, ∂(v, t) == u^3)` makes the optimizer do nothing
```julia
using InfiniteOpt, Ipopt
m = InfiniteModel(optimizer_with_attributes(Ipopt.Optimizer, "print_level" => 5));
@infinite_parameter(m, t in [0, 8], num_supports = 101)
@variables(m, begin
    # state variables
    x, Infinite(t)
    v, Infinite(t)
    u, Infinite(t)
end)
@objective(m, Min, ∫(abs2(x) + abs2(v) + abs2(u), t))
@constraint(m, x(0) == 1)
@constraint(m, v(0) == 0)
@constraint(m, ∂(x, t) == v)
@constraint(m, ∂(v, t) == u)
InfiniteOpt.optimize!(m)

t_opt = value.(t);
x_opt = value.(x);
v_opt = value.(v);
u_opt = value.(u)
plot(t_opt, [x_opt v_opt u_opt], label=["x" "v" "u"], c=[:blue :orange :green])
```
### With `dv = u`
![image](https://github.com/infiniteopt/InfiniteOpt.jl/assets/3797491/adba988a-53e3-4ed3-88c9-43453c45cc80)

### With `dv = u^3`
![image](https://github.com/infiniteopt/InfiniteOpt.jl/assets/3797491/0cc51fe0-198a-47ae-ac76-ae72fd02c021)

**Desktop (please complete the following information):**
```
julia> VERSION
v"1.10.2"

  [20393b10] InfiniteOpt v0.5.8
  [b6b21f68] Ipopt v1.6.2
```

Side question, why does `u` always start at 0? There is no constraint on `∂(v, t) == u` that should force this?

**Comment by baggepinnen** [comment]
Hmm, this seems strange, if I have zero penalty on `u` and `v` I still get the same solution, I can't see how this can be a local optimum?
```julia
using InfiniteOpt, Ipopt
m = InfiniteModel(optimizer_with_attributes(Ipopt.Optimizer, "print_level" => 5));
@infinite_parameter(m, t in [0, 8], num_supports = 101)
@variables(m, begin
    # state variables
    x, Infinite(t)
    v, Infinite(t)
    u, Infinite(t)
end)
@objective(m, Min, ∫(abs2(x) + 0*abs2(v) + 0*abs2(u), t))
@constraint(m, x(0) == 1)
@constraint(m, v(0) == 0)
@constraint(m, ∂(x, t) == v)
@constraint(m, ∂(v, t) == u^3)
InfiniteOpt.optimize!(m)

t_opt = value.(t);
x_opt = value.(x);
v_opt = value.(v);
u_opt = value.(u)
plot(t_opt, [x_opt v_opt u_opt], label=["x" "v" "u"], c=[:blue :orange :green])
```

**Comment by pulsipher** [comment]
A key thing to keep in mind is that nonconvex NLPs are can very sensitive to the initial guess when solved locally. In this case, changing the initial guess of u gives a different answer:
```julia
using InfiniteOpt, Ipopt, Plots
m = InfiniteModel(Ipopt.Optimizer)
@infinite_parameter(m, t in [0, 8], num_supports = 101)
@variables(m, begin
    # state variables
    x, Infinite(t)
    v, Infinite(t)
    # control variable
    u, Infinite(t), (start = -1)
end)
@objective(m, Min, ∫(abs2(x) + abs2(v) + abs2(u), t))
@constraint(m, x(0) == 1)
@constraint(m, v(0) == 0)
@constraint(m, ∂(x, t) == v)
@constraint(m, ∂(v, t) == u^3)
optimize!(m)

t_opt = value(t)
x_opt = value(x)
v_opt = value(v)
u_opt = value(u)
plot(t_opt, [x_opt v_opt u_opt], label=["x" "v" "u"], c=[:blue :orange :green])
```
![image](https://github.com/infiniteopt/InfiniteOpt.jl/assets/33848311/a056298a-0315-4625-9b8b-903599dee84f)

Changing the initial guess to `-10` gets a another local solution:
![image](https://github.com/infiniteopt/InfiniteOpt.jl/assets/33848311/d279a158-0f74-40c8-9a22-5b6b7d4f7fc0)

This all just highlights just how important good initial guess values are for NLPs. You can also try using a global solver like Alpine, SCIP, or Baron, but these may take a while to converge.

**Comment by baggepinnen** [comment]
Interesting, it looks like the optimal solution has impulsive control action, and the solvers are having a hard time finding this. Here's a solution with 101 support points obtained by SCIP, with a fairly large optimality gap, but it looks very similar in nature to an optimal solution with tiny optimality gap obtained for 11 support points.

![image](https://github.com/infiniteopt/InfiniteOpt.jl/assets/3797491/ee333f09-ab7f-469e-bd3a-31940f6f9e3d)

Thanks for your help and sorry for my confused issue!

**Comment by pulsipher** [comment]
No need to apologize, I am glad we were able to clear things up.
