### ISSUE TITLE
`constant_over_collocation` only in dev docs?

### ISSUE THREAD

**Issue by baggepinnen** [infiniteopt/InfiniteOpt.jl#350]
Hey there :wave: 

Back in October, a PR was merged adding a function `constant_over_collocation`. I can't find this function in the docs of the latest release, but [I can find it in the dev docs](https://infiniteopt.github.io/InfiniteOpt.jl/dev/manual/expression/#InfiniteOpt.constant_over_collocation-Tuple{GeneralVariableRef,%20GeneralVariableRef}). The latest release https://github.com/infiniteopt/InfiniteOpt.jl/releases/tag/v0.5.9 was made after the PR was merged, and is indicated to contain the PR, how come it won't show up in the docs? The function appears to only be available on the main branch as well, not in the 0.5.9 release.

Thanks!

**Comment by pulsipher** [comment]
Good question. Currently, `constant_over_collocation` and several other changes are currently on the development version only (i.e., the master branch). These will all be released with v0.6.0 which I anticipate should be ready in the next week or so.

Version v0.5.9 was only a patch release that had some bug fixes. The release notes erroneously included a lot of other PRs. I have now corrected the release notes accordingly.

**Comment by baggepinnen** [comment]
Thanks for clarifying!
