### ISSUE TITLE
[FEATURE] Query expression and parameter function names.

### ISSUE THREAD

**Issue by DarioSlaifsteinSk** [infiniteopt/InfiniteOpt.jl#367]
**The feature I'd like**
Just as we query variables with:

```julia
    x = all_variables(model)
    name = name.(x)
    value = value.(x)
```
It would be nice to have something similar for parameter functions:
```julia
    fns = all_expressions/parameters(model)
    name = name.(fns)
    value = value.(fns)
```
**What I currently do about this**
Otherwise you have to know the name beforehand and hardcode it.
In particular, when summarizing results in a `Dict` or `DataFrame`

**Comment by pulsipher** [comment]
Thanks for the recommendation. Can you provide a more precise use case for this? One thing you can always do is leverage the object dictionary:
```julia
for (sym, obj) in object_dictionary(model)
    println(name.(obj)) 
    println(value.(obj))
end
```
This will provide any named objects added to `model`.

**Comment by DarioSlaifsteinSk** [comment]
yes, partially. Because when you
```julia
typeof(obj)
```
the type of an InfVar `x(t)` is `GeneralVariableRef` and of a parameter function `fn` is also a `GeneralVariableRef`.
Personally I like to store exogenous information (param_functions), actions and states in different dictionaries for analysis. 
When making such dictionaries I store all the vars on one side and the parameter functions on another one, and to develop an automation has deemed harder than just coding:

```julia
merge!(xdict, Dict("function1"=>value.(model[:function1]),
                        "function2"=>value.(model[:function2]),
                        ...
                        "functionN"=>value.(model[:functionN]),
```

**Comment by DarioSlaifsteinSk** [comment]
oh! I forgot to click on "comment"
this is much nicer than what i was doing!
